<?php

declare(strict_types=1);

namespace Drupal\Tests\helfi_azure_fs\Kernel;

use Drupal\Core\DependencyInjection\ContainerBuilder;
use Drupal\flysystem\Adapter\AdapterDefinition;
use Drupal\flysystem\Adapter\AdapterDriverInterface;
use Drupal\flysystem\Adapter\FilesystemFactoryInterface;
use Drupal\helfi_azure_fs\Plugin\Flysystem\Adapter\Azure;
use Drupal\helfi_azure_fs\StreamWrapper\AzureStreamWrapper;
use Drupal\KernelTests\KernelTestBase;
use League\Flysystem\Filesystem;
use League\Flysystem\FilesystemOperator;
use League\Flysystem\Local\LocalFilesystemAdapter;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses;

/**
 * Tests the Azure adapter driver integration with Flysystem.
 *
 * These tests attempt to catch if Flysystem updates break the features we
 * rely on.
 */
#[Group('helfi_azure_fs')]
#[RunTestsInSeparateProcesses]
class FlysystemRoutesTest extends KernelTestBase {

  /**
   * {@inheritdoc}
   */
  protected static $modules = [
    'file',
    'image',
    'key',
    'system',
    'flysystem',
    'helfi_azure_fs',
  ];

  /**
   * {@inheritdoc}
   */
  public function register(ContainerBuilder $container): void {
    // Flysystem registers the stream wrappers of the settings.php schemes
    // when the container is built, so the settings must be defined before.
    $this->setSetting('flysystem', [
      'azure' => [
        'driver' => 'helfi_azure',
        'public_url_base' => 'https://mock-name.blob.core.windows.net/mock-container',
        'config' => [
          'name' => 'mock-name',
          'token' => 'mock-token',
          'container' => 'mock-container',
          'endpointSuffix' => 'core.windows.net',
          'protocol' => 'https',
        ],
      ],
    ]);
    parent::register($container);
  }

  /**
   * Tests that the driver is discovered and used for the 'azure' scheme.
   */
  public function testAdapterDriver() : void {
    /** @var \Drupal\flysystem\Adapter\AdapterDriverPluginManager $manager */
    $manager = $this->container->get('plugin.manager.flysystem.adapter_driver');
    $this->assertTrue($manager->hasDefinition('helfi_azure'));

    /** @var \Drupal\flysystem\Adapter\FilesystemFactoryInterface $factory */
    $factory = $this->container->get('flysystem.filesystem_factory');
    $this->assertInstanceOf(Azure::class, $factory->getDriver('azure'));
    $this->assertInstanceOf(Filesystem::class, $factory->getFilesystem('azure'));
    $this->assertEquals('https://mock-name.blob.core.windows.net/mock-container', $factory->getDefinition('azure')->publicUrlBase);

    // File URLs are generated from the public URL base.
    $url = $this->container->get('file_url_generator')->generateAbsoluteString('azure://folder/test file.jpg');
    $this->assertEquals('https://mock-name.blob.core.windows.net/mock-container/folder/test%20file.jpg', $url);
  }

  /**
   * Tests the image style derivative URLs.
   */
  public function testDerivativeUrl() : void {
    $wrapper = $this->container->get('stream_wrapper_manager')->getViaScheme('azure');
    $this->assertInstanceOf(AzureStreamWrapper::class, $wrapper);

    // Store the files locally instead of the blob storage. Virtual file
    // system doesn't support locking.
    $filesystem = new Filesystem(new LocalFilesystemAdapter('vfs://root/azure', writeFlags: 0));
    $wrapper->setFactory(new class($this->container->get('flysystem.filesystem_factory'), $filesystem) implements FilesystemFactoryInterface {

      public function __construct(
        private readonly FilesystemFactoryInterface $inner,
        private readonly FilesystemOperator $filesystem,
      ) {
      }

      /**
       * {@inheritdoc}
       */
      public function getDriver(string $scheme): AdapterDriverInterface {
        return $this->inner->getDriver($scheme);
      }

      /**
       * {@inheritdoc}
       */
      public function getDriverById(string $driverId): AdapterDriverInterface {
        return $this->inner->getDriverById($driverId);
      }

      /**
       * {@inheritdoc}
       */
      public function getSchemes(): array {
        return $this->inner->getSchemes();
      }

      /**
       * {@inheritdoc}
       */
      public function getFilesystem(string $scheme): FilesystemOperator {
        return $this->filesystem;
      }

      /**
       * {@inheritdoc}
       */
      public function hasScheme(string $scheme): bool {
        return $this->inner->hasScheme($scheme);
      }

      /**
       * {@inheritdoc}
       */
      public function getDefinition(string $scheme): AdapterDefinition {
        return $this->inner->getDefinition($scheme);
      }

    });
    $generator = $this->container->get('file_url_generator');

    // Missing derivatives are generated by Drupal.
    $url = $generator->generateAbsoluteString('azure://styles/thumbnail/azure/folder/missing file.jpg');
    $this->assertStringStartsWith('http://localhost/', $url);
    $this->assertStringEndsWith('/styles/thumbnail/azure/folder/missing%20file.jpg', $url);

    // Existing derivatives are served from the blob storage.
    $filesystem->write('styles/thumbnail/azure/folder/test file.jpg', 'derivative');
    $url = $generator->generateAbsoluteString('azure://styles/thumbnail/azure/folder/test file.jpg');
    $this->assertEquals('https://mock-name.blob.core.windows.net/mock-container/styles/thumbnail/azure/folder/test%20file.jpg', $url);

    // Other files are not affected.
    $url = $generator->generateAbsoluteString('azure://folder/missing file.jpg');
    $this->assertEquals('https://mock-name.blob.core.windows.net/mock-container/folder/missing%20file.jpg', $url);
  }

  /**
   * Tests that the legacy image style route is still available.
   */
  public function testImageStyleRoute() : void {
    $route = $this->container->get('router.route_provider')
      ->getRouteByName('flysystem.image_style');

    $this->assertEquals('/_flysystem/styles/{image_style}/{scheme}', $route->getPath());
    $this->assertEquals('azure', $route->getDefault('required_derivative_scheme'));
  }

}
